akaza-core/akaza/user_language_model.py
ibus-akaza/ibus_akaza/ui.py

save user-language-model in background thread.

---

ibus-akaza/ibus-akaza-debug.sh
ibus-akaza/src/commands.rs
ibus-akaza/src/context.rs
ibus-akaza/src/input_mode.rs
ibus-akaza/src/keymap.rs
ibus-akaza/src/main.rs
ibus-akaza/src/wrapper_bindings.rs
ibus-akaza/wrapper.c
ibus-akaza/wrapper.h
ibus-sys/bindgen.sh
ibus-sys/src/engine.rs
ibus-sys/src/lib.rs
ibus-sys/src/prop_list.rs
ibus-sys/src/property.rs

Add Proplist

---

ibus-akaza/src/commands.rs
ibus-akaza/src/context.rs
ibus-akaza/src/keymap.rs
ibus-sys/src/lookup_table.rs

Support PageUp/PageDown

---

akaza-data/src/subcmd/make_dict.rs
libakaza/src/graph/graph_builder.rs
libakaza/src/graph/graph_resolver.rs
libakaza/src/graph/lattice_graph.rs
libakaza/src/graph/word_node.rs

Rename WordNode.kanji to WordNode.surface

---

akaza-data/src/subcmd/dump_unigram_dict.rs
akaza-data/src/subcmd/make_stats_system_bigram_lm.rs
libakaza/src/lm/base.rs
libakaza/src/lm/system_unigram_lm.rs

remove as_id_map.

---

Cargo.lock
akaza-data/src/main.rs
akaza-data/src/subcmd/check.rs
akaza-data/src/subcmd/learn_corpus.rs
ibus-akaza/ibus-akaza-debug.sh
libakaza/Cargo.toml
libakaza/src/engine/bigram_word_viterbi_engine.rs
libakaza/src/graph/graph_resolver.rs
libakaza/src/graph/segmenter.rs
libakaza/src/kana_trie/cedarwood_kana_trie.rs
libakaza/src/kana_trie/mod.rs
libakaza/src/user_side_data/user_data.rs

Cedarwood user data

---

.github/workflows/ci-simple.yml
.github/workflows/model.yml

actions-rs/toolchain was abondoned https://github.com/actions-rs/toolchain/issues/216

Switch to dtolnay/rust-toolchain

---

.github/workflows/model.yml

生成されるakaza-data.tar.gzに含まれるファイルのパスをakaza-data/から始まるようにした。

model.ymlの微調整

---

libakaza/src/romkan.rs
romkan/atok.yml

Add atok style romkan mapping

---

akaza-data/Makefile
akaza-data/src/main.rs
akaza-data/src/subcmd/evaluate.rs
ibus-akaza/ibus-akaza-debug.sh
libakaza/src/engine/bigram_word_viterbi_engine.rs
libakaza/src/keymap.rs
libakaza/src/resource.rs
libakaza/src/romkan.rs

https://github.com/akaza-im/akaza-default-model/issues/5

AKAZA_* の環境変数を廃止する

---

libakaza/src/dict/loader.rs
libakaza/src/kana_kanji/marisa_kana_kanji_dict.rs

https://github.com/akaza-im/akaza/issues/210

辞書のキャッシュの invalidation をちゃんと実装する

---

ibus-akaza/src/context.rs
libakaza/src/engine/bigram_word_viterbi_engine.rs

https://github.com/akaza-im/akaza-default-model/issues/5

ローマ字変換を engine から外す

---

akaza-conf/src/conf.rs
akaza-data/src/main.rs
akaza-data/src/subcmd/check.rs
akaza-data/src/subcmd/evaluate.rs
libakaza/src/config.rs
libakaza/src/dict/loader.rs
libakaza/src/engine/bigram_word_viterbi_engine.rs
libakaza/src/kana_kanji/marisa_kana_kanji_dict.rs

- [akaza-data evaluate で model_dir を選択必須にした](https://github.com/akaza-im/akaza/commit/934ff439fd4fb147955a42b69cfdbd198df51c6e)
- [akaza-data では cache を更新しないようにする](https://github.com/akaza-im/akaza/commit/a82d158e2ee8911a2ad3230707502253243ebe88)
https://github.com/akaza-im/akaza-default-model/issues/5

make evaluate の調整

---

akaza-data/src/main.rs
akaza-data/src/subcmd/check.rs

https://github.com/akaza-im/akaza/issues/225

check コマンドで辞書のパスをハードコードしているのをやめる

---

akaza-data/src/tokenizer/base.rs
akaza-data/src/tokenizer/vibrato.rs

https://github.com/akaza-im/akaza-default-model/issues/12

`井伊家` の複合語化処理にアドホックな対応を追加

---

libakaza/src/dict/skk/read.rs

kk /株式会社/ のようなアルファベットのみのものを辞書から読まないように

---

akaza-data/src/subcmd/learn_corpus.rs
akaza-data/src/wordcnt/wordcnt_unigram.rs
libakaza/src/graph/graph_builder.rs
libakaza/src/graph/graph_resolver.rs
libakaza/src/graph/lattice_graph.rs
libakaza/src/lm/base.rs
libakaza/src/lm/on_memory/on_memory_system_unigram_lm.rs
libakaza/src/lm/system_unigram_lm.rs

今後の #252 をやりやすくするための施策。
モデルのフォーマットが変わるので注意。

[非互換] コストの計算を利用時にするように変更。

---

ibus-akaza/src/context.rs

ライブコンバージョンモードでも、lookup table

---

akaza-data/src/main.rs
akaza-data/src/subcmd/tokenize.rs
akaza-data/src/tokenizer/base.rs
akaza-data/src/tokenizer/vibrato.rs

https://github.com/akaza-im/akaza-default-model/issues/14

add kana-preferred mode for akaza-data tokenizer.

---

libakaza/src/graph/lattice_graph.rs

Reverts akaza-im/akaza#276 Close #289

Revert "平仮名を優先する。 #252"
